name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: cd Web-Cypress && npm install
      - name: Prettier
        run: cd Web-Cypress && npm run prettier
      - name: Lint
        run: cd Web-Cypress && npm run lint
      - name: Tests
        run: cd Web-Cypress && npm run cy:qa:check.mac

