name: "Send Allure report to Slack"
on: push
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const summary = await fetch('https://1kurochkin.github.io/test_git_actions/docs/widgets/summary.json');
            const summaryBody = await summary.json()
            console.log(summaryBody)




