name: "Send Allure report to Slack"
on: push
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allureReportLink = "https://1kurochkin.github.io/test_git_actions/docs"
            const summary = await fetch(allureReportLink + '/widgets/summary.json').then((res) => res.json());
            const suites = await fetch(allureReportLink + '/widgets/suites.json').then((res) => res.json());
            
            await fetch(`${{secrets.SLACK_WEBHOOK_URL}}`, {method: 'POST', body: JSON.stringify({
              status: "success", 
              mention: "D070P94QG5C",
              if_mention: "always",
              text: 
                `Allure Report Link: ${allureReportLink}\n` + 
                `Total test suites executed: ${suites.total}\n` +
                `Summary: ${JSON.stringify(summary.statistic)}\n\n` +
                `${suites.items.map(suite => `- ${suite.name}: ${JSON.stringify(suite.statistic)}\n\n`).join('')}`
            })})




